// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFby4XtFEfeAyhGDqWwuoRBpi1HBPnn9c',
    appId: '1:16043473379:web:6f092781f33e6aa465c8d6',
    messagingSenderId: '16043473379',
    projectId: 'oedsted-festival-app',
    authDomain: 'oedsted-festival-app.firebaseapp.com',
    storageBucket: 'oedsted-festival-app.appspot.com',
    measurementId: 'G-BGRZHPT8DV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr_V6RtjweLqtP9beZGIOrymDMjZWX7wQ',
    appId: '1:16043473379:android:763224266eca92cb65c8d6',
    messagingSenderId: '16043473379',
    projectId: 'oedsted-festival-app',
    storageBucket: 'oedsted-festival-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX33dWREGRlwyRTs0EVwqZegubqKrCDV0',
    appId: '1:16043473379:ios:5b771725fb31fc6765c8d6',
    messagingSenderId: '16043473379',
    projectId: 'oedsted-festival-app',
    storageBucket: 'oedsted-festival-app.appspot.com',
    iosClientId: '16043473379-f8pq0otifl86lrk4m3jojkjan8dpo2q1.apps.googleusercontent.com',
    iosBundleId: 'com.example.festivalVolunteerApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX33dWREGRlwyRTs0EVwqZegubqKrCDV0',
    appId: '1:16043473379:ios:b7621b7a4781c78965c8d6',
    messagingSenderId: '16043473379',
    projectId: 'oedsted-festival-app',
    storageBucket: 'oedsted-festival-app.appspot.com',
    iosClientId: '16043473379-0hruvips5uq4a1oi90j5t1935tm5l0lv.apps.googleusercontent.com',
    iosBundleId: 'com.example.festivalVolunteerApplication.RunnerTests',
  );
}